#This script will use the graph generated by snap and add randomized weights to each edge as well as generate the v,u edge for u,v edge.
#Check if graph is connected or not before doing this process.
#To use the new set, cut the last line and past it to be the first line.
#Make sure there is no blank last line.

#Use the following commands in python in the directory that contains this file to create the connected graph.
#import snap
#G1=snap.GenRndGnm(snap.PUNGraph, 10, 5)
#print(snap.IsConnected(G1))

#Use the following command only if the print from the previous command returns True meaning graph is connected.
#snap.SaveEdgeList(G1, "tempset.txt", "Save as tab-separated list of edges")


import random
f1= open("../tempset.txt","r")
f2= open("temp13","w")
edgeset = set()
set_verts = set()
x = f1.readline()
x = f1.readline()
x = f1.readline()
x = f1.readline()
for x in f1:
    x = x.split("\t")
    weight = random.randint(1,500)
    edgeset.add(tuple([int(x[0]), int(x[1].rstrip()), weight]))
#    edgeset.add(tuple([int(x[1].rstrip()), int(x[0]), weight]))
    set_verts.add(int(x[0]))
    set_verts.add(int(x[1].rstrip()))
for edge in edgeset:
    y = str(edge[0]) + ',' + str(edge[1]) + ',' + str(edge[2]) + '\n'
    f2.write(y)
f2.write(str(len(set_verts))+','+str(len(edgeset)))
f2.close()
f1.close()